[package]
name = "mpd-display-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.27.2"
egui_speedy2d = "0.5.0"
log = "0.4.21"
speedy2d = "2.1.0"
simple_logger = { version = "1.11", default-features = false, features = ["colors"] }
mpd = "0.1.0"

